name: Deploy Dependency Review to Org

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'The repository to push to'
        required: true
      org:
        description: 'The organization to push to'
        required: true

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/create-github-app-token@v1
        id: app-token-source
        with:
          app-id: ${{ secrets.GHAS_APP_ID }}
          private-key: ${{ secrets.GHAS_APP_KEY }}
          owner: theztefan-enterprise-test
          repositories: dependency-review-config

      - uses: actions/create-github-app-token@v1
        id: app-token-target
        with:
          app-id: ${{ secrets.GHAS_APP_ID }}
          private-key: ${{ secrets.GHAS_APP_KEY }}
          owner: ${{ github.event.inputs.org }}
          repositories: ${{ github.event.inputs.repo }}
      
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token-source.outputs.token }}
        
      - name: Pushes to org_repo
        env:
          $TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          TOKEN: ${{ steps.app-token-target.outputs.token }}
        run: |
          git config --global user.email "github-action@github.com"
          git config --global user.name "GitHub Action Bot"
          git config --global push.autoSetupRemote true
          #git remote add target https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/${{ github.event.inputs.org }}/${{ github.event.inputs.repo }}
          #git push -u target main
          #git remote add target https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/${{ github.event.inputs.org }}/${{ github.event.inputs.repo }}.git
          #git remote add target https://$TOKEN@github.com/${{ github.event.inputs.org }}/${{ github.event.inputs.repo }}.git
          #git push target

          git push --mirror https://${TOKEN}@github.com/${{ github.event.inputs.org }}/${{ github.event.inputs.repo }}

          
